---
title: "Checklist for Incoming FPCs and Deck Leads"
site: distill::distill_website
---

```{r panelset, echo=FALSE}
library(xaringanExtra)
xaringanExtra::use_panelset()
```

::: c-screen

::::: {.panelset}


::: {.panel}

## Eastern Bering Sea {.panel-name}

Download checklist [here](../downloaded/EBS_checklist_in.docx)

```{r Subset Checklist documents for BS, results = 'asis', echo = F}
checklist_items <- subset(x = full_site0, 
                          sub_page == "checklist_in" & Survey %in% c("bs", "all"))
main_bullets <- unique(checklist_items$subsection)

string <- "<ul>"
for(isection in main_bullets) {
  subdf <- subset(x = checklist_items, subset = subsection == isection)
  string <- paste0(string, paste0("<h2>", isection, "</h2>"))

  for(irow in 1:nrow(subdf)) {
  type <- ifelse(test = is.na(subdf$url_loc[irow]),
                 yes = "text",
                 no = "link")

  string <- paste0(string,
                   paste0("<li>",
                          ifelse(type == "link", yes = "[", no = ""),
                          subdf$title[irow],
                          ifelse(type == "link",
                                 yes = paste0("](",
                                              subdf$url_loc[irow],
                                              ")"),
                                 no = ""),
                          "</li>"))
  }
  string <- paste0(string, "<br>")
}

string <- paste0(string, "</ul>" )
cat(string)
```

```{r create EBS doc, echo = F, results="hide"}
survey_name <- "Eastern Bering Sea"
rmarkdown::render(input = "create_checklist_worddoc.Rmd", 
                  output_format = "word_document", 
                  output_file = "downloaded/EBS_checklist_in.docx",
                  params = list(checklist_items = checklist_items,
                                main_bullets = main_bullets,
                                survey_name = survey_name))
```

:::


::: {.panel}

## AI/GOA {.panel-name}

Download checklist [here](../downloaded/AIGOA_checklist_in.docx)

```{r Subset Checklist documents for AIGOA, results = 'asis', echo = F}
checklist_items <- subset(x = full_site0, 
                          sub_page == "checklist_in" & Survey %in% c("goa", "ai", "all"))
main_bullets <- unique(checklist_items$subsection)

string <- "<ul>"
for(isection in main_bullets) {
  subdf <- subset(x = checklist_items, subset = subsection == isection)
  string <- paste0(string, paste0("<h2>", isection, "</h2>"))

  for(irow in 1:nrow(subdf)) {
  type <- ifelse(test = is.na(subdf$url_loc[irow]),
                 yes = "text",
                 no = "link")

  string <- paste0(string,
                   paste0("<li>",
                          ifelse(type == "link", yes = "[", no = ""),
                          subdf$title[irow],
                          ifelse(type == "link",
                                 yes = paste0("](",
                                              subdf$url_loc[irow],
                                              ")"),
                                 no = ""),
                          "</li>"))
  }
  string <- paste0(string, "<br>")
}

string <- paste0(string, "</ul>" )
cat(string)
```

```{r create AIGOA doc, echo = F, results="hide"}
survey_name <- "Aleutian Islands/Gulf of Alaska"
rmarkdown::render(input = "create_checklist_worddoc.Rmd", 
                  output_format = "word_document", 
                  output_file = "downloaded/AIGOA_checklist_in.docx",
                  params = list(checklist_items = checklist_items,
                                main_bullets = main_bullets,
                                survey_name = survey_name))
```

:::


:::::

:::

