---
title: "Alaska Fish ID by Family"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, results = "asis")
```

```{r}
guides_data <- readr::read_csv("./data/species_id_data.csv") %>%
  mutate(size_cm = as.character(size_cm),
         species_code = as.character(species_code)) %>%
  replace(is.na(.), "")

grps <- guides_data %>%
  select(group_short, group_long) %>%
  unique() %>%
  mutate(
    group_page = paste0("./zz_", make_clean_names(group_short), ".html"),
    link = paste0("[", group_long, "](", group_page, ")")
  ) %>%
  arrange(group_short)

links <- paste0(grps$link, collapse = "<br>")

```


`r links`


```{r, eval = remake_species_pages}
## this chunk generates all individual species and family pages; takes a long time to run

for (k in 1:nrow(grps)) {
  group_data <- guides_data %>%
    filter(group_short == grps$group_short[k])

  group_title <- make_clean_names(group_data$group_short[1])

  fam <- group_data$group_long[1]
  spp <- unique(group_data$species)
  spp <- spp[spp != "subgroup"]


  ## making subgroup pages
  subgrps <- unique(group_data$subgroup)
  subgrps[is.na(subgrps)] <- ""
  subgrps <- sort(subgrps, decreasing = TRUE) #blank subgrps last
  
  
  
  if (length(subgrps) > 1) { # generates subgroup level pages
    if(fam == "Rockfishes"){ #rockfishes are a strange case with nested subgroups
      cols <- c("red", "red/black", "black", "striped/spotted")
      for(ii in 1:length(cols)){
      fam_page <- TRUE
      subtitle <- str_to_title(cols[ii])
      rf_data <- group_data %>%
        separate(subgroup, into = c("color_cat", "subgroup"), sep = " ", extra = "merge") %>%
        mutate(subgroup = tolower(str_remove(subgroup, "category; |category")),
                subgroup = ifelse(is.na(subgroup), "", subgroup)) 
      
      page_data <- rf_data %>%
        filter(species != "subgroup") %>%
        filter(tolower(color_cat) == cols[ii]) %>%
        group_by(species) %>%
        mutate(n = 1:n()) %>%
        filter(n == 1)
      
      page <- paste0("zz_", group_title, "_", str_remove(cols[ii], "/"), ".html")
      fp <- FALSE
     
      subgrps <- unique(tolower(page_data$subgroup))
      
      rmarkdown::render(paste0("template_family_pages.Rmd"),
        output_dir = "./docs/",
        output_file = page)
      rm(ncols, colnms, page)
      

      for(jj in 1:length(subgrps)){
        subtitle <- subgrps[jj]
        fam_page <- FALSE
        page_data <- rf_data %>%
          filter(tolower(color_cat) == cols[ii]) %>%
          filter(tolower(subgroup) == subgrps[[jj]])
          
      page <- paste0("zz_", group_title, "_", str_remove(cols[ii], "/"), "_subpg_", jj, ".html")
      
      rmarkdown::render(paste0("template_family_pages.Rmd"),
        output_dir = "./docs/",
        output_file = page)
      rm(ncols, colnms, page)
      }
  } 
      } else {
    
    fp <- FALSE
    fam_page <- FALSE
    for (kk in 1:length(subgrps)) {
      subtitle <- str_to_title(subgrps[kk])

      page_data <- group_data %>%
        mutate(subgroup = ifelse(is.na(subgroup), "", subgroup)) %>%
        filter(subgroup == subgrps[kk]) %>%
        group_by(species) %>%
        mutate(n = 1:n()) %>%
        filter(n == 1)

    page <- paste0("zz_", group_title, "_subpg", kk, ".html")
      
     rmarkdown::render(paste0("template_family_pages.Rmd"),
        output_dir = "./docs/",
        output_file = page)
    
     rm(ncols, colnms, page)
    }

    }
  }



  # generates group-level page
  fam_page <- TRUE
  
  if(fam == "Rockfishes"){
    fp <- TRUE
    subtitle <- "Color Categories"
    page_data <- rf_data %>%
          mutate(subgroup = tolower(color_cat))
    subgrps <- cols
    
    } else {
    
  if (all(grepl(group_data$family[[1]], group_data$family))) {
    subtitle <- group_data$family[1]
 
     } else {
    subtitle <- ""
     }
    
  page_data <- group_data
  
  }
  
  page <- paste0("zz_", group_title, ".html")
  
  
  rmarkdown::render(paste0("template_family_pages.Rmd"),
    output_dir = "./docs/",
    output_file = page)


  
  
  
  
  

  # making species pages
  for (ll in 1:length(spp)) {
    species_page <- group_data %>%
      filter(species != "subgroup") %>%
      filter(species == spp[ll])

    title <- str_to_title(species_page$common_name[1])
    subtitle <- paste0("*", species_page$species[1], "*")
    
    #trying to shorten file name
    sp_pg <- str_replace(str_remove(species_page$species[1], "[a-z]+"), "\\s", "")
    
    page <- paste0("zz_", group_title, "_", sp_pg, ".html")

    rmarkdown::render(paste0("template_species_pages.Rmd"),
      output_dir = "./docs/",
      output_file = page
    )
  }
}
```
