---
title: "Species Identification Guides"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE)
```


```{r}
all_files <- taxa_guides %>%
  dplyr::select(title, section, subsection, url_loc) %>%
  dplyr::mutate(filename = basename(url_loc),
                taxa = case_when(
                  section %in% c("bird", "mammal") ~ "Birds and Mammals",
                  section == "fish" ~ "Fishes",
                  section == "algae" ~ "Algae",
                  TRUE ~ "Inverts"
                ),
                url_loc = stringr::str_replace(url_loc, "\\.","\\.."),
                reference = paste0("[", title, "](", gsub(" ","%20", url_loc), ")"))
```


```{r, results = "asis"}
fish_id <- paste0("[ID by Taxa](./Species_ID_Fish_ID_by_Taxa.html)")

tabl <- all_files %>%
  dplyr::mutate(Taxa = ifelse(!is.na(subsection), subsection, section)) %>%
  dplyr::mutate(Taxa = ifelse(Taxa == "fish", NA, str_to_sentence(Taxa))) %>%
  dplyr::arrange(taxa, Taxa, title)

options(knitr.kable.NA = '')

sec <- unique(tabl$taxa)

for(i in 1:length(sec)){
  tmp <- tabl %>%
    dplyr::filter(taxa == sec[[i]]) %>%
    dplyr::select(Taxa, Reference = reference) %>%
    dplyr::arrange(!is.na(Taxa), Taxa)
  
  if(sec[i] == "Fishes"){
      cat(paste0("## ", sec[[i]], " — ", fish_id, ""), '\n \n \n')
  } else {
    cat(paste0("## ", sec[[i]]), '\n \n \n')
  }

  k <- kableExtra::kable(tmp, format = "html", linesep = "",
                  align = rep("l", 2)) %>%
  kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::collapse_rows(1, latex_hline = "custom", valign = "top") 
  
  cat(k)
}

rm(all_files, page_dat, tabl, tmp, fish_id, i, k, page_desc,
   page_title, sec)
```

