---
title: "`r page_desc`"
description: "`r page_title`"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE)
```


```{r}
str00 <- ""

if (nrow(page_dat) != 0) {
  page_dat <- page_dat %>% 
    dplyr::arrange(section, subsection, title) %>%
    mutate(subsection = (subsection))

  # For each section, subset data
  for (i in 1:length(unique(page_dat$section))) {
    
    temp0 <- page_dat %>% 
      dplyr::filter(section == unique(page_dat$section)[i])
    
    ## for each subsection, further subset data from section
    str0 <- ""
    for (ii in 1:length(unique(x = temp0$subsection))) {
      
      temp <- temp0 %>% 
        dplyr::filter(subsection == unique(x = temp0$subsection)[ii])
      
      # compile text that will go on the page
      str000 <- paste( paste0("|      ", temp$title_link, # title
                              ifelse(test = is.na(x = temp$subtitle), 
                                     yes = "", 
                                     no = paste0(": *", temp$subtitle, "*")), # subtitle
                              # " ",temp$Links_inline,
                              "
", temp$descrip, "

"), collapse = "")

      if (unique(x = temp$subsection)[1] != "") {
        
        str000 <- paste0("

### ", (unique(x = temp$subsection)[1]), "

", str000)
      }
      str0 <- paste0(str0, str000)
      
    }
    
    if (unique(x = temp$section)[1] != "") {
      str0 <- paste0("

## ", (unique(x = temp0$section)[1]), "

", str0)
    }
    str00 <- paste0(str00, str0)
  }
  
}
```

`r str00 `

```{=html}
<script>
function myFunction() {
var input, filter, table, tr, td, i, txtValue;
input = document.getElementById("myInput");
filter = input.value.toUpperCase();
table = document.getElementById("myTable");
tr = table.getElementsByTagName("tr");
for (i = 0; i < tr.length; i++) {
td = tr[i].getElementsByTagName("td")[1];
if (td) {
txtValue = td.textContent || td.innerText;
if (txtValue.toUpperCase().indexOf(filter) > -1) {
tr[i].style.display = "";
} else {
tr[i].style.display = "none";
}
}       
}
}
</script>
```


-----------------------------------

`r rm(temp, temp0, i, ii, page_desc, page_title, str0, str00, str000, page_dat)`